version: '3.8'

services:
  # Development service
  portfolio-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: robinttw/portfolio:dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    profiles:
      - dev

  # Production service
  portfolio-prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: robinttw/portfolio:latest
    ports:
      - "80:80"
    profiles:
      - prod 